name: Mirror to Bitbucket

on:
  push:
    branches:
      - main

# Ép hệ thống chạy trên nền tảng Node.js 24 mới nhất để xóa sạch cảnh báo
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  mirror_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Bitbucket
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          # Làm sạch các cấu hình remote cũ để tránh xung đột
          git remote remove bitbucket || true
          
          # Chèn trực tiếp Username và Token vào URL theo chuẩn HTTPS Git
          git remote add bitbucket https://$BITBUCKET_USERNAME:$BITBUCKET_TOKEN@bitbucket.org/qtetech-global/industrial-scientific-catalog.git
          
          # Tiến hành ép đồng bộ toàn bộ dữ liệu và tag sang Bitbucket
          git push bitbucket main --force --tags
