name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Xóa thông tin cũ để tránh xung đột
          git remote rm hf || true
          
          # 2. Cấu hình định danh
          git config --global user.email "tuan-qte@qtetech.com"
          git config --global user.name "QTE-Robot"
          
          # 3. Thêm remote mới với Token (Sử dụng cấu hình chuẩn của HF)
          # Lưu ý: nguyenhuutuan-qte là username cá nhân của bạn sở hữu Token
          git remote add hf https://nguyenhuutuan-qte:$HF_TOKEN@huggingface.co/datasets/QTE-Technologies/industrial-technical-archive
          
          
