name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Cấu hình danh tính cho Robot
          git config --global user.email "tuan-qte@qtetech.com"
          git config --global user.name "QTE-Robot"
          
          # 2. Ép buộc đồng bộ (Force Push) để GitHub làm chủ hoàn toàn
          # Thay 'tuan-qte' bằng username HF của bạn nếu cần, nhưng dùng token là đủ
          git push --force https://qtetech:${{ secrets.HF_TOKEN }}@huggingface.co/datasets/QTE-Technologies/industrial-technical-archive main
