name: Sync to Hugging Face hub
on:
  push:
    branches: [main] # Robot sẽ chạy mỗi khi bạn push lên nhánh main

  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Cấu hình robot đẩy dữ liệu sang HF
          git push --force https://tuan-qte:$HF_TOKEN@huggingface.co/datasets/QTE-Technologies/industrial-technical-archive main
